# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20161011_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='data',
            new_name='date',
        ),
    ]
