# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20161013_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='ad',
        ),
        migrations.AddField(
            model_name='ad',
            name='images',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ads.Images'),
        ),
    ]
