# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20161013_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='images',
            new_name='image',
        ),
    ]
