# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 08:36
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20161013_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to=ads.models.get_image_filename, verbose_name='Image'),
        ),
    ]
