# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 08:38
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20161013_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ads.models.get_image_filename, verbose_name='Image'),
        ),
    ]
