# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20161013_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='image',
            new_name='images',
        ),
    ]
