# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20161013_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Image'),
        ),
    ]
