# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:23
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_auto_20161013_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.ImageField(blank=True, null=True, upload_to=ads.models.get_image_filename, verbose_name='Image'),
        ),
    ]
